env:
  browser: true
  commonjs: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
plugins:
  - react
  - '@typescript-eslint'
settings: 
  react:
    version: 'latest'
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  '@typescript-eslint/no-empty-function': off
  # '@typescript-eslint/no-empty-function':
  #   - error
  # eslint no-empty-function: 
  #   - error 
  #   allow: 
  #     - generatorFunctions
  #     - arrowFunctions
